export const accessProtectedApiPaths = [
  "/api/v1/tree",
  "/api/v1/tags",
  "/api/v1/recent",
  "/api/v1/favorites",
  "/api/v1/trash",
  "/api/v1/me",
  "/api/v1/pages",
  "/api/v1/pages/*",
  "/api/v1/search",
  "/api/v1/answer",
  "/api/v1/imports",
  "/api/v1/imports/:id",
  "/api/v1/imports/:id/apply",
  "/api/v1/imports/google/authorize",
  "/api/v1/imports/google/picker-config",
  "/api/v1/exports",
  "/api/v1/exports/*",
  "/api/v1/account-links",
  "/api/v1/account-links/*",
  "/api/v1/admin/*",
] as const;
